import "./globals.css";
import { Sora } from "next/font/google";
import Navbar from "@/components/views/Navbar";
import Wrapper from "@/components/shared/Wrapper";
import Footer from "@/components/views/Footer";
// import TopLabel from '@/components/views/TopLabel';

const inter = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Wrapper>
        <Navbar />
        <div className='min-h-screen'>
          {children}
        </div>
        <Footer />
      </Wrapper>
    </body>
  </html>
  );
}
